spring:
  application:
    name: itoken-service-sso
  boot:
    admin:
      client:
        url: http://192.168.76.128:8084
  zipkin:
    base-url: http://192.168.76.128:9411
  datasource:
    druid:
      url: jdbc:mysql://192.168.76.128:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false #开发时关闭缓存，不然没法看到实时页面
    mode:  LEGACYHTML5 #用非严格的html5
    encodign: UTF-8
    servlet:
      context-type: text/html

server:
  port: 8503

feign:
  circuitbreaker:
    enabled: true

mybatis:
  configuration:
    cached-enabled: true
  type-aliases-package: com.lucifer.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.76.128:8761/eureka/,http://192.168.76.128:8861/eureka/,http://192.168.76.128:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info