spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://192.168.76.128:8084
  zipkin:
    base-url: http://192.168.76.128:9411

server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.76.128:8761/eureka/,http://192.168.76.128:8861/eureka/,http://192.168.76.128:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info