spring:
  application:
    name: itoken-service-upload

server:
  port: 8505

#fastdfs.base.url: http://192.168.73.99:8888/
fastdfs.base.url: http://192.168.73.133/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.73.133:22122

