spring:
  application:
    name: itoken-gateway
  cloud:
    gateway:
      default-filter:
        - PreserveHostHeader
      discovery:
        locator:
          enabled: true
      routes:
        - id: backend-admin
          uri: lb://itoken-web-admin
          predicates:
            - Path=/backend/admin/**
#          filters:
#            - StripPrefix=2   #为了达到和zuul一样的路由效果(去除前n个级前缀)

        - id: backend-posts
          uri: lb://itoken-web-posts
          predicates:
            - Path=/backend/posts/**
#          filters:
#            - StripPrefix=2

server:
  port: 8769