spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
#          uri: https://gitee.com/the-father-of-great-god-wang/spring-cloud-config.git
          uri: https://github.com/cyfyang/itoken-config.git
#          uri: https://github.com/cyfyang/microservicecloud-config.git
          search-paths: respo
#          username: cyf_yang@163.com
#          password: xxxxxx
#          strict-host-key-checking: false
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info